services:
  - type: web
    name: Web_full_ITMO_course
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000